# Generated by Django 4.1.3 on 2023-03-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_todo_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Todo_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='Todo_title',
            new_name='title',
        ),
    ]
