# Generated by Django 4.1.3 on 2023-03-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_history_history_takedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todo_title', models.CharField(max_length=100)),
                ('Todo_detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
